<a href="https://colab.research.google.com/github/abyachla20/Data_Mining/blob/main/breastcancerprediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn import tree

In [2]:
dataset = pd.read_csv('breast_cancer_dataset.csv')
dataset

Age_At_The_Time_Of_Mammography  ... Patients_Study_ID
0                                  62  ...                 1
1                                  65  ...                 2
2                                  69  ...                 3
3                                  64  ...                 4
4                                  63  ...                 5
...                               ...  ...               ...
39993                              80  ...             36711
39994                              78  ...             36712
39995                              77  ...             36712
39996                              66  ...             36713
39997                              61  ...             36714

[39998 rows x 13 columns]

In [3]:
dataset["Is_Binary_Indicator_Of_Cancer_Diagnosis"] = pd.factorize(dataset.Is_Binary_Indicator_Of_Cancer_Diagnosis)[0]
dataset["Comparison_Mammogram_From_Mammography"] = pd.factorize(dataset.Comparison_Mammogram_From_Mammography)[0]
dataset["Family_History_Of_Breast_Cancer"] = pd.factorize(dataset.Family_History_Of_Breast_Cancer)[0]
dataset["Current_Use_Of_Hormone_Therapy"] = pd.factorize(dataset.Current_Use_Of_Hormone_Therapy)[0]
dataset["Binary_Indicator"] = pd.factorize(dataset.Binary_Indicator)[0]
dataset["History_Of_Breast_Biopsy"] = pd.factorize(dataset.History_Of_Breast_Biopsy)[0]
dataset["Is_Film_Or_Digital_Mammogram"] = pd.factorize(dataset.Is_Film_Or_Digital_Mammogram)[0]
dataset["Cancer_Type"] = pd.factorize(dataset.Cancer_Type)[0]

In [4]:
print(dataset)

       Age_At_The_Time_Of_Mammography  ... Patients_Study_ID
0                                  62  ...                 1
1                                  65  ...                 2
2                                  69  ...                 3
3                                  64  ...                 4
4                                  63  ...                 5
...                               ...  ...               ...
39993                              80  ...             36711
39994                              78  ...             36712
39995                              77  ...             36712
39996                              66  ...             36713
39997                              61  ...             36714

[39998 rows x 13 columns]


In [5]:
dataset = dataset.drop(labels="Patients_BI_RADS_Breast_Density", axis=1)
dataset = dataset.drop(labels="Body_Mass_Index", axis=1)
dataset = dataset.drop(labels="Radiologists_Assessment", axis=1)
dataset = dataset.drop(labels="Age_At_The_Time_Of_Mammography", axis=1)
dataset = dataset.drop(labels="Patients_Study_ID", axis=1)
dataset

Is_Binary_Indicator_Of_Cancer_Diagnosis  ...  Cancer_Type
0                                            0  ...            0
1                                            0  ...            0
2                                            0  ...            0
3                                            0  ...            0
4                                            0  ...            0
...                                        ...  ...          ...
39993                                        0  ...            0
39994                                        0  ...            0
39995                                        0  ...            0
39996                                        0  ...            0
39997                                        0  ...            0

[39998 rows x 8 columns]

In [6]:
dataset = dataset.to_numpy()

In [7]:
print(dataset)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
dataTraining = np.concatenate((dataset[0:9999, :], dataset[9999:19999, :]),
                              axis=0)
dataTesting = np.concatenate((dataset[19999:29998, :], dataset[29998:39998, :]),
                             axis=0)

In [9]:
print(dataTraining)
len(dataTraining)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


19999

In [10]:
print(dataTesting)
len(dataTesting)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 1 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


19999

In [11]:
inputTraining = dataTraining[:, 0:7]
inputTesting = dataTesting[:, 0:7]
labelTraining = dataTraining[:, 7]
labelTesting = dataTesting[:, 7]
print(labelTraining)
len(labelTraining)

[0 0 0 ... 0 0 0]


19999

In [12]:
model = tree.DecisionTreeClassifier()

In [13]:
model = model.fit(inputTraining, labelTraining)

In [14]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ",labelTesting)
print("HasilPrediksi : ", hasilPrediksi)

Label Sebenarnya :  [0 0 0 ... 0 0 0]
HasilPrediksi :  [0 0 0 ... 0 0 0]


In [15]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar : ", prediksiBenar, "data")
print("Prediksi Salah : ", prediksiSalah, "data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar :  19974 data
Prediksi Salah :  25 data
Akurasi :  99.87499374968748 %
