<a href="https://colab.research.google.com/github/abyachla20/Data_Mining/blob/main/Prepocessing_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [40]:
dataset = pd.read_csv('Data2.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [41]:
print(x)

[['CPU' 16.0 2500000.0]
 ['RAM' 28.0 1200000.0]
 ['VGA' 12.0 4000000.0]
 ['SSD' 32.0 1000000.0]
 ['SSD' 24.0 nan]
 ['Casing' 25.0 450000.0]
 ['VGA' nan 800000.0]
 ['Motherboard' 30.0 700000.0]
 ['Cooler' 35.0 900000.0]
 ['Fan' 45.0 300000.0]]


In [42]:
print(y)

['Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'No']


In [43]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] =imputer.transform(x[:, 1:3])

In [44]:
print(x)

[['CPU' 16.0 2500000.0]
 ['RAM' 28.0 1200000.0]
 ['VGA' 12.0 4000000.0]
 ['SSD' 32.0 1000000.0]
 ['SSD' 24.0 1316666.6666666667]
 ['Casing' 25.0 450000.0]
 ['VGA' 27.444444444444443 800000.0]
 ['Motherboard' 30.0 700000.0]
 ['Cooler' 35.0 900000.0]
 ['Fan' 45.0 300000.0]]


In [46]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [47]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 16.0 2500000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 28.0 1200000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 12.0 4000000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 32.0 1000000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 24.0 1316666.6666666667]
 [1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 25.0 450000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 27.444444444444443 800000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 30.0 700000.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 35.0 900000.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 45.0 300000.0]]


In [48]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [50]:
print(y)

[1 0 0 1 1 0 1 1 1 0]


In [51]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,  random_state=1)

In [52]:
print(x_train)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 27.444444444444443 800000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 24.0 1316666.6666666667]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 16.0 2500000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 32.0 1000000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 28.0 1200000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 30.0 700000.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 35.0 900000.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 25.0 450000.0]]


In [53]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 12.0 4000000.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 45.0 300000.0]]


In [54]:
print(y_train)

[1 1 1 1 0 1 1 0]


In [55]:
print(y_test)

[0 0]


In [56]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:] = sc.transform(x_test[:, 4:])

In [57]:
print(x_train)

[[1.0 0.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.5773502691896258 2.6457513110645903 0.048904307356633196
  -0.5269607450036939]
 [1.0 0.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  1.7320508075688774 -0.3779644730092272 -0.5894255991931128
  0.35605455743492803]
 [0.0 1.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.5773502691896258 -0.3779644730092272 -2.0719982853731684
  2.37844444366532]
 [1.0 0.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  1.7320508075688774 -0.3779644730092272 0.893147086986943
  -0.18514836986616293]
 [1.0 0.0 0.0 0.0 0.0 -0.3779644730092272 2.6457513110645903
  -0.5773502691896258 -0.3779644730092272 0.15186074389691515
  0.15666400527136815]
 [1.0 0.0 0.0 0.0 0.0 2.6457513110645903 -0.3779644730092272
  -0.5773502691896258 -0.3779644730092272 0.5225039154419291
  -0.6978669325724595]
 [1.0 0.0 0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.5773502691896258 -0.3779644730092272 1.449111844304464
  -0.

In [58]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272
  -0.5773502691896258 2.6457513110645903 -2.8132846284631965
  4.9420372571968025]
 [1.0 0.0 0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272
  -0.5773502691896258 -0.3779644730092272 3.3023277020295336
  -1.3814916828475217]]
